//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public clientes()
        {
            this.lugarVisita = new HashSet<lugarVisita>();
        }
    
        public int id_clientes { get; set; }
        public string nombres { get; set; }
        public int edad { get; set; }
    
        public virtual ICollection<lugarVisita> lugarVisita { get; set; }
    }
}
