//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class lugarVisita
    {
        public int id_lugarVisita { get; set; }
        public string nombre { get; set; }
        public string tipo_cliente { get; set; }
        public decimal precio { get; set; }
        public Nullable<int> id_clientes { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
